    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - name: Install pytest
            run: |
              pip install pytest
          - uses: actions/checkout@v2
          - name: Install Dependencies
            run: |
              pip install -t dependencies -r requirements.txt
          - uses: education/autograding@v1